//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Status { get; set; }
        public string Categories { get; set; }
        public string Runtime { get; set; }
        public string Cluster { get; set; }
        public string OtherParams { get; set; }
        public string TestResultFile { get; set; }
    }
}
